[armnn] compilation error - unused parameter
correction for occurences of compilation error below, when compilation
switch ENABLE_ARMNN_CAFFE is disabled.

error: unused parameter '[parameter name]' [-Werror=unused-parameter]

Signed-off-by: Julien Vuillaumier <julien.vuillaumier@nxp.com>